version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: orderdesk-postgres
    environment:
      POSTGRES_DB: orderdesk
      POSTGRES_USER: orderdesk
      POSTGRES_PASSWORD: orderdesk
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderdesk -d orderdesk"]
      interval: 5s
      retries: 10

  app:
    image: talonew/orderdesk:0.1.0
    depends_on:
      flyway:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/orderdesk
      DB_USER: orderdesk
      DB_PASSWORD: orderdesk
      JAVA_OPTS: -Dserver.port=8080 
      SPRING_FLYWAY_ENABLED: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
 

  flyway:
    image: flyway/flyway:latest
    depends_on:
      db:
        condition: service_healthy
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/orderdesk
      FLYWAY_USER: orderdesk
      FLYWAY_PASSWORD: orderdesk
    volumes:
      - ./app/src/main/resources/db/migration:/flyway/sql:ro

  nginx:
    image: nginx:latest
    container_name: orderdesk-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
