server:
  port: 8080

spring:
  application:
    name: orderdesk
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orderdesk}
    username: ${DB_USER:orderdesk}
    password: ${DB_PASSWORD:orderdesk}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
